name: Docker Image stable

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - feature/debian-image
      - feature/ubuntu

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:    
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels: true
          repository: devopsmindset/packer-windows-update
          tags: ubuntu